
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://gnradjbemavirhzehhyw.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducmFkamJlbWF2aXJoemVoaHl3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODU1NTIzOSwiZXhwIjoyMDg0MTMxMjM5fQ.Ods_iPrzSyiAzCoRpOQbKXBZkuW1OWYhQ3oZFMl8-1Y";
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const projects = [
    { title: 'LuxeFashion Global', category: 'E-Commerce', image_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Premium fashion marketplace with AI-driven style recommendations and AR virtual try-on.', tech: ['Next.js', 'Shopify Plus', 'TensorFlow.js'], client: 'Luxe Brands Ltd', duration: '5 months', year: '2024', color: 'pink' },
    { title: 'UrbanPicks Store', category: 'E-Commerce', image_url: 'https://images.unsplash.com/photo-1472851294608-415522f97817?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Multi-vendor marketplace for streetwear enthusiasts with real-time auction functionality.', tech: ['React', 'Node.js', 'Socket.io'], client: 'Urban Retail', duration: '4 months', year: '2024', color: 'blue' },
    { title: 'EcoGrocery Direct', category: 'E-Commerce', image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Sustainable grocery delivery app with route optimization and carbon footprint tracking.', tech: ['Vue.js', 'Firebase', 'Google Maps API'], client: 'Green Earth', duration: '3 months', year: '2023', color: 'green' },
    { title: 'TechGear Pro', category: 'E-Commerce', image_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'B2B electronics component sourcing platform with bulk ordering and ERP integration.', tech: ['Angular', '.NET Core', 'Azure'], client: 'TG Industries', duration: '6 months', year: '2023', color: 'blue' },
    { title: 'Skyline Realty', category: 'Real Estate', image_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Luxury property portal featuring 360-degree virtual tours and mortgage calculators.', tech: ['React', 'Matterport API', 'AWS'], client: 'Skyline Group', duration: '4 months', year: '2024', color: 'purple' },
    { title: 'UrbanNest Rentals', category: 'Real Estate', image_url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Short-term rental platform for digital nomads with automated booking management.', tech: ['Next.js', 'Supabase', 'Stripe Connect'], client: 'UrbanNest', duration: '3 months', year: '2024', color: 'orange' },
    { title: 'Commercial Hub', category: 'Real Estate', image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Investment analysis tool for commercial real estate portfolios.', tech: ['Python', 'Django', 'D3.js'], client: 'Hub Invest', duration: '5 months', year: '2023', color: 'gray' },
    { title: 'NovaBank Mobile', category: 'Fintech', image_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Neobank mobile application interface with spending analytics and goal tracking.', tech: ['React Native', 'Node.js', 'Plaid'], client: 'Nova Financial', duration: '6 months', year: '2024', color: 'emerald' },
    { title: 'CryptoVault', category: 'Fintech', image_url: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Secure non-custodial wallet dashboard for managing multi-chain assets.', tech: ['Web3.js', 'Solidity', 'Rust'], client: 'BlockSecure', duration: '4 months', year: '2024', color: 'indigo' },
    { title: 'InsureTech Dash', category: 'Fintech', image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'AI-powered claim processing dashboard for insurance agents.', tech: ['Vue.js', 'Python ML', 'PostgreSQL'], client: 'InsureOne', duration: '5 months', 'year': '2023', color: 'cyan' },
    { title: 'VitalCheck Teleheatlh', category: 'Healthcare', image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'HIPAA-compliant telemedicine platform connecting patients with specialists worldwide.', tech: ['WebRTC', 'React', 'Node.js'], client: 'Vital Health', duration: '7 months', year: '2024', color: 'red' },
    { title: 'Mindful Space', category: 'Healthcare', image_url: 'https://images.unsplash.com/photo-1544367563-12123d8965cd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Meditation and wellness app with personalized daily routines and mood tracking.', tech: ['Flutter', 'Firebase', 'Sanity CMS'], client: 'Mindful Corp', duration: '3 months', year: '2023', color: 'teal' },
    { title: 'PharmaSupply B2B', category: 'Healthcare', image_url: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Supply chain management system for pharmaceutical distributors.', tech: ['Java', 'Spring Boot', 'React'], client: 'PharmaLink', duration: '8 months', year: '2023', color: 'blue' },
    { title: 'Wanderlust Travels', category: 'Travel', image_url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Immersive travel booking platform with customized itinerary planning features.', tech: ['Next.js', 'Mapbox', 'Amadeus API'], client: 'Wanderlust Inc', duration: '4 months', year: '2024', color: 'orange' },
    { title: 'DineEasy Reserve', category: 'Travel', image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Restaurant table reservation system with dynamic floor plan management.', tech: ['Vue.js', 'Laravel', 'Twilio'], client: 'Dine Group', duration: '3 months', year: '2024', color: 'red' },
    { title: 'Hotelier Pro', category: 'Travel', image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Property management system for independent boutique hotels.', tech: ['React', 'Go', 'PostgreSQL'], client: 'Hotelier Systems', duration: '6 months', year: '2023', color: 'purple' },
    { title: 'LearnWave Academy', category: 'Education', image_url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Interactive learning management system with video courses and live quizzes.', tech: ['MERN Stack', 'AWS S3', 'Vimeo API'], client: 'LearnWave', duration: '5 months', year: '2024', color: 'yellow' },
    { title: 'KidCode Jr', category: 'Education', image_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Gamified coding platform for children ages 6-12.', tech: ['React', 'Phaser.js', 'Node.js'], client: 'KidCode', duration: '4 months', year: '2023', color: 'green' },
    { title: 'UniConnect', category: 'Education', image_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Networking and mentorship portal for university alumni and students.', tech: ['Django', 'PostgreSQL', 'Redis'], client: 'Global University', duration: '3 months', year: '2023', color: 'blue' },
    { title: 'InnovateTech Corp', category: 'Corporate', image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'High-performance corporate website with investor relations portal.', tech: ['Next.js', 'Strapi', 'Vercel'], client: 'InnovateTech', duration: '2 months', year: '2024', color: 'indigo' },
    { title: 'LogiStream CMS', category: 'Corporate', image_url: 'https://images.unsplash.com/photo-1586880244406-556ebe35f282?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Internal content management system for global logistics documentation.', tech: ['Angular', 'SharePoint', 'Azure'], client: 'Logi Worldwide', duration: '5 months', year: '2024', color: 'blue' },
    { title: 'LegalFlow Pro', category: 'Corporate', image_url: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Case management software for mid-sized law firms.', tech: ['React', '.NET', 'SQL Server'], client: 'Legal Partners', duration: '6 months', year: '2023', color: 'slate' },
    { title: 'HR Pulse', category: 'Corporate', image_url: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Employee engagement and performance review platform.', tech: ['Vue.js', 'Ruby on Rails', 'PostgreSQL'], client: 'PeopleFirst', duration: '4 months', year: '2023', color: 'rose' },
    { title: 'Studio Noir Portfolio', category: 'Creative', image_url: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Minimalist 3D portfolio for an award-winning design agency.', tech: ['Three.js', 'React', 'WebGL'], client: 'Studio Noir', duration: '2 months', year: '2024', color: 'black' },
    { title: 'PhotoLens Gallery', category: 'Creative', image_url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'High-resolution photography archive with smart tagging and licensing.', tech: ['Next.js', 'Cloudinary', 'Stripe'], client: 'Lens Media', duration: '3 months', 'year': '2023', color: 'violet' },
    { title: 'MusicStream App', category: 'Creative', image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Indie music streaming platform for unsigned artists.', tech: ['Flutter Web', 'Firebase', 'FFmpeg'], client: 'IndieSound', duration: '5 months', year: '2024', color: 'purple' },
    { title: 'Bistro Reserve', category: 'Food', image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Online ordering and table booking system for a restaurant chain.', tech: ['React', 'Express', 'MongoDB'], client: 'Bistro Chain', duration: '3 months', year: '2024', color: 'orange' },
    { title: 'Coffee Culture', category: 'Food', image_url: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Subscription management platform for specialty coffee beans.', tech: ['Shopify Liquid', 'Js', 'Recharge'], client: 'Coffee Culture', duration: '2 months', 'year': '2023', color: 'brown' },
    { title: 'FarmToTable', category: 'Food', image_url: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Marketplace connecting local organic farmers directly with consumers.', tech: ['Next.js', 'Stripe', 'PostgreSQL'], client: 'Local Farms', duration: '4 months', year: '2023', color: 'green' },
    { title: 'CleanOcean Initiative', category: 'Non-Profit', image_url: 'https://images.unsplash.com/photo-1484291470158-b8f8d608850d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Donation and awareness platform for ocean conservation efforts.', tech: ['WordPress', 'React', 'Donation API'], client: 'Ocean NGO', duration: '2 months', 'year': '2024', color: 'cyan' },
    { title: 'EduForAll', category: 'Non-Profit', image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', description: 'Volunteer management system for rural education programs.', tech: ['React', 'Firebase', 'Google Maps'], client: 'Edu Foundation', duration: '3 months', 'year': '2023', color: 'yellow' }
];

async function seedProjects() {
    console.log("Seeding projects...");
    const { error } = await supabase.from("projects").insert(projects);
    if (error) console.error("Error inserting projects:", error);
    else console.log("Successfully inserted projects!");
}

seedProjects();
