// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceifvdpfzpqhaglhguir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlaWZ2ZHBmenBxaGFnbGhndWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDQ5OTYsImV4cCI6MjA2NTQ4MDk5Nn0.Y29f7yFBKyTSbTutIvLaONgUC0SaBEfgLS4bIHLmBD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);