// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnradjbemavirhzehhyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducmFkamJlbWF2aXJoemVoaHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NTUyMzksImV4cCI6MjA4NDEzMTIzOX0.HVTQXpWI_sIjgvkdaj6C2vIpqEFXax3weLUVWxAMoro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);